### ISSUE TITLE
Error trying to install package

### ISSUE THREAD

**Issue by ghost** [amoussard/sftp-deployment#10]
Installing “SFTP-deployment@0.5.0” failed. Less…

npm http GET https://registry.npmjs.org/MD5
npm http GET https://registry.npmjs.org/ftp
npm http GET https://registry.npmjs.org/util
npm http GET https://registry.npmjs.org/node-dir
npm http GET https://registry.npmjs.org/ssh2
npm http 503 https://registry.npmjs.org/node-dir
npm ERR! registry error parsing json
npm http 503 https://registry.npmjs.org/MD5
npm ERR! registry error parsing json
npm http 503 https://registry.npmjs.org/ftp
npm ERR! registry error parsing json
npm http 503 https://registry.npmjs.org/ssh2
npm ERR! registry error parsing json
npm http 200 https://registry.npmjs.org/util
npm http GET https://registry.npmjs.org/util/-/util-0.10.3.tgz
npm http 200 https://registry.npmjs.org/util/-/util-0.10.3.tgz
npm http GET https://registry.npmjs.org/node-dir
npm http GET https://registry.npmjs.org/MD5
npm http GET https://registry.npmjs.org/ftp
npm http GET https://registry.npmjs.org/ssh2
npm http 503 https://registry.npmjs.org/node-dir
npm ERR! registry error parsing json
npm http 503 https://registry.npmjs.org/MD5
npm ERR! registry error parsing json
npm http 503 https://registry.npmjs.org/ssh2
npm ERR! registry error parsing json
npm http 200 https://registry.npmjs.org/ftp
npm http GET https://registry.npmjs.org/ftp/-/ftp-0.3.7.tgz
npm http 200 https://registry.npmjs.org/ftp/-/ftp-0.3.7.tgz
npm http GET https://registry.npmjs.org/node-dir
npm http GET https://registry.npmjs.org/MD5
npm http GET https://registry.npmjs.org/ssh2
npm http 503 https://registry.npmjs.org/ssh2
npm ERR! registry error parsing json
npm http 503 https://registry.npmjs.org/MD5
npm ERR! registry error parsing json
npm http 503 https://registry.npmjs.org/node-dir
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token <
npm ERR! 
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>503 No healthy backends</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 503 No healthy backends</h1>
npm ERR!     <p>No healthy backends</p>
npm ERR!     <h3>Guru Meditation:</h3>
npm ERR!     <p>XID: 1974154108</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR! 
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/npm-registry-client/lib/request.js:203:23)
npm ERR!     at Request.self.callback (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.2.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/joshua/.atom/.apmrc" "install" "/var/folders/xl/9m08qq8d6mdd69n6dxs133000000gn/T/d-114512-59275-lzw0yj/package.tgz" "--target=0.11.10" "--arch=x64"
npm ERR! cwd /private/var/folders/xl/9m08qq8d6mdd69n6dxs133000000gn/T/apm-install-dir-114512-59275-1io4qoi
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! type unexpected_token
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/xl/9m08qq8d6mdd69n6dxs133000000gn/T/apm-install-dir-114512-59275-1io4qoi/npm-debug.log
npm ERR! not ok code 0

**Comment by amoussard** [comment]
Hi @ghost,

There is always a problem ?
Reopen if it's always present.
