### ISSUE TITLE
cannot install SFTP deployment on the new version of atom

### ISSUE THREAD

**Issue by fraidoonk** [amoussard/sftp-deployment#121]
Installing “SFTP-deployment@1.0.2” failed.Hide output…

npm WARN deprecated MD5@1.3.0: deprecated, use lowercase 'md5@2.x' from now on
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Fraidoon\\AppData\\Local\\atom\\app-1.6.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Fraidoon\\AppData\\Local\\atom\\app-1.6.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Fraidoon\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Fraidoon\\.atom\\.apmrc" "install" "C:\\Users\\Fraidoon\\AppData\\Local\\Temp\\d-116225-7788-jfgoq3\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: expand-home-dir@'>=0.0.2 <0.0.3'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["2.0.0","0.0.3"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'SFTP-deployment'
npm ERR! notarget

**Comment by constant-null** [comment]
have the same problem here

**Comment by lightinen** [comment]
the same. win10, x64

**Comment by inu1255** [comment]
the same. atom 1.6.0

**Comment by thenexus00** [comment]
We have found the same, No longer works on windows 10 since its last update. Same Atom version on windows 7 it actually works.

**Comment by dibalaj** [comment]
Same problem on Windows 10, Atom 1.6.0. Does anyone have a solution for this?

**Comment by sebwegscheider** [comment]
It's not only Windows, same problem on OS X, Atom 1.6.0.

**Comment by igarciaes** [comment]
Ubuntu 14.04

Installing “SFTP-deployment@1.0.2” failed.
npm WARN deprecated MD5@1.3.0: deprecated, use lowercase 'md5@2.x' from now on
npm ERR! Linux 3.13.0-61-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/igarcia/.atom/.apm/.apmrc" "--userconfig" "/home/igarcia/.atom/.apmrc" "install" "/tmp/d-116230-8075-7sk3uq/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: expand-home-dir@'>=0.0.2 <0.0.3'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["2.0.0","0.0.3"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'SFTP-deployment'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116230-8075-lnj07w/npm-debug.log

**Comment by mkadi90** [comment]
the same on Linux Mint 17.3

**Comment by rodrigograca31** [comment]
@mkadi90 I can confirm that!
It's not working on Linux Mint 17.3 (64bits), Atom 1.4.0:


```
Installing “sftp-deployment@1.0.2” failed.Hide output…

npm WARN deprecated MD5@1.3.0: deprecated, use lowercase 'md5@2.x' from now on
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/user/.atom/.apm/.apmrc" "--userconfig" "/home/user/.atom/.apmrc" "install" "/tmp/d-11634-30130-58pri9/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: expand-home-dir@'>=0.0.2 <0.0.3'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["2.0.0","0.0.3"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'SFTP-deployment'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11634-30130-18t1v18/npm-debug.log

```

**Comment by mkadi90** [comment]
Update to Atom 1.6.2 solve problem.

**Comment by rodrigograca31** [comment]
@mkadi90 I can also confirm that! :+1:

**Comment by amoussard** [comment]
Hi all,

The problem is still there ?

Thank you for your feedback.

**Comment by rodrigograca31** [comment]
Not with the latest atom version....

**Comment by amoussard** [comment]
Ok, thank you for the fast response @rodrigograca31 !

**Comment by lauyader** [comment]
El mismo problema en la versión 1.8 con ubuntu 16.04 64.bits

**Comment by staticvoidzach** [comment]
I'm having the same issue on 1.28.1
