### ISSUE TITLE
Upload on save

### ISSUE THREAD

**Issue by whuhacker** [amoussard/sftp-deployment#13]
It would be great if the plugin could add an option "upload_on_save", so that the file will be uploaded automatically as soon as I edited and saved it.

**Comment by rafaelrp** [comment]
+1

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This feature will be added at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
