### ISSUE TITLE
[Ubuntu] Doesn't create config file when asked for it.

### ISSUE THREAD

**Issue by andersonkoester** [amoussard/sftp-deployment#14]
When I click on "Map to Remote", Atom shows me an alert to I choose SFTP or FTP, when I choose one of them, nothing happens.

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
