### ISSUE TITLE
sftp doesnt upload correctly

### ISSUE THREAD

**Issue by heihachi** [amoussard/sftp-deployment#17]
When i upload a file with sftp it uploads to the home folder using the remote_path without any / or \'s 

in the config i have remote_path set to
"remote_path": "/var/www/",

in /home/heihachi its lists as 
heihachi@code-breaker:~$ ls
development
downloads
exclude.txt
project-fire -> /var/www/
varwww
\var\www\config.dist.php

I was looking around in the source code and cant find any place where it would replace it

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
