### ISSUE TITLE
bad path

### ISSUE THREAD

**Issue by raspberry59** [amoussard/sftp-deployment#22]
When upload files to a remote server generated the wrong way.
Example: \home\<account_name>\qq\qq.php 
Used by the client operating system: windows 8.1 
Used server operating system: Linux 3.2

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
