### ISSUE TITLE
SFTP connection not closed after upload

### ISSUE THREAD

**Issue by gdscei** [amoussard/sftp-deployment#23]
SFTP connections don't appear to be closed after uploading a file.
After a day's work, there are tons of sftp processes active on the server.

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
