### ISSUE TITLE
Uncaught SyntaxError: Unexpected token } 

### ISSUE THREAD

**Issue by jon-weiss** [amoussard/sftp-deployment#24]
I'm getting the error:

Uncaught SyntaxError: Unexpected token } 

when trying to upload / download files. I'm pretty new to all of this, so bare with me!

I've set up a project and created the deployment-config.json file with all of the correct info.

Anyone have any advice? Thanks for the help.

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

The configuration file is a json file, so it must be well formatted (no coma on the last parameter).

Thank you for using our work ! :)
