### ISSUE TITLE
Config file doesn't show up when mapping to remote

### ISSUE THREAD

**Issue by kevin-george** [amoussard/sftp-deployment#27]
I opened up a folder and then tried to map to remote, it shows me a dialog window to select from either ftp/sftp. Selecting either of them doesn't show any config file.
I'm on a windows 7 machine and just got the windows alpha release. Am i doing something wrong or anything i'm missing?

**Comment by alanhouser** [comment]
Ditto. Thanks @kevin-george. Lots of time wasted on this package fo-realz.

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
