### ISSUE TITLE
File uploading error

### ISSUE THREAD

**Issue by miguelcanijo** [amoussard/sftp-deployment#29]
Updated atom into 0.129 I get this error every time I try to upload a file:

Uncaught TypeError: Cannot read property 'getPath' of undefined 
../.atom/packages/SFTP-deployment/lib/filesystem/FileManager.js:98

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
