### ISSUE TITLE
Links in your manifest are not http

### ISSUE THREAD

**Issue by smlombardi** [amoussard/sftp-deployment#31]
The links that show up in the package's property pane in Atom (where you can enable/disable) settings are "git://" links: the package home page and report issues etc.

![screen shot 2014-09-27 at 11 15 49 am](https://cloud.githubusercontent.com/assets/835148/4431138/37974dfe-4659-11e4-992f-0e9c269cb8b9.png)

When clicked they generate an error instead of opening Safari like other packages do

![screen shot 2014-09-27 at 11 14 42 am](https://cloud.githubusercontent.com/assets/835148/4431140/47bab7f2-4659-11e4-8dbe-aa8c3d1f3a9f.png)

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by bcabanes** [comment]
Hi,
This is fixed in the next release. https://github.com/amoussard/sftp-deployment/commit/0f3c7914c459e3419937b3412b957ed61b5c1bcc
