### ISSUE TITLE
Error while trying to connect  'getPath'

### ISSUE THREAD

**Issue by Lerogero** [amoussard/sftp-deployment#35]
![image](https://cloud.githubusercontent.com/assets/5865044/4937121/9c77a7ba-65c0-11e4-8739-2da80c66b282.png)

Currently getting this error 'getPath' error whilst trying to connect to a server via SFTP

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
