### ISSUE TITLE
Package not showing details on connection_error

### ISSUE THREAD

**Issue by Trudko** [amoussard/sftp-deployment#36]
Hi, first of all thank you for a plugin :)

When I tried the plugin on first time I got general error The connection has encountered an error. Problem is that this error didn't help me much so I had to debug to get details. What about adding data variable to message so instead of 
```
createErrorMessage("The connection has encountered an error.", value);
```
in MessageObserver (line 49) have 
```
createErrorMessage("The connection has encountered an error. " + data, value);
```
so it is obvious what the problem is.

**Comment by amoussard** [comment]
Hi @Trudko ,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This feature will be present at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
