### ISSUE TITLE
Packet integrity error and  Authentication failure

### ISSUE THREAD

**Issue by Trudko** [amoussard/sftp-deployment#37]
Hi, I am trying your plugin on Windows 8.1 and when I try to login using ssh key with config

```
{
  "type": "sftp",
  "host": "myhost",
  "user": "me",
  "port": "22",
  "remote_path": "/path/to/folder",
  "ssh_key_file": "path/to/ssh"
}
```
but I get error "Disconnected by host (PROTOCOL_ERROR): Packet integrity error."

If I try to log in using  password

```
{
  "type": "sftp",
  "host": "myhost",
  "user": "me",
  "password": "password"
  "port": "22",
  "remote_path": "/path/to/folder",
  "ssh_key_file": "path/to/ssh"
}
```
Then I get error "Authentication failure. Available authentication methods: publickey,keyboard-interactive"

What am I doing wrong?

**Comment by webdesignberlin** [comment]
Trudko said:
> Hi, I am trying your plugin on Windows 8.1 and when I try to login using ssh key with config
> {
>   "type": "sftp",
>  "host": "myhost",
>   "user": "me",
>   "port": "22",
>   "remote_path": "/path/to/folder",
>   "ssh_key_file": "path/to/ssh"
>  }
> but I get error "Disconnected by host (PROTOCOL_ERROR): Packet integrity error."

Same Problem on Windows 7 and MacOSX 10.10.2 after Updating node from 0.10.x to 0.12. 
Any ideas?

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
I will note that bug and see it after the next release (1.1.0).

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

This problem is still alive ?
My previous work should have corrected it.
