### ISSUE TITLE
Where is the config file?

### ISSUE THREAD

**Issue by rbrooks** [amoussard/sftp-deployment#38]
When your extension generates its config file, neither the software nor your docs, say where that file is.

**Comment by alanhouser** [comment]
Agree. I'm browsing the files and not finding it either.

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
I will add documentation for that.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
