### ISSUE TITLE
Error when uploading from sidebar

### ISSUE THREAD

**Issue by alexbet** [amoussard/sftp-deployment#39]
Getting this error when trying to upload file from sidebar by right-clicking on the file and choosing "FTP/SFTP Upload selection" (see screen shot). 
![screen_shot_2014-12-28_at_8_47_43_pm](https://cloud.githubusercontent.com/assets/3966760/5565639/2105bf2c-8ed3-11e4-8d88-43c3a2646b37.png)

**Comment by Pooky** [comment]
I think this is coused by new Atom API. I solved this problem by following steps:

1) Open lib/filesystem/FileManager.js
2) At line 98 find this code: ```self.addToStack($(this).view().getPath());```
3) Replace it with this code: ```self.addToStack($("span", this).data("path"));```
4) Restart ATOM / or reload VIEW->RELOAD

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
