### ISSUE TITLE
Uncaught Error: ENOTDIR, open '/home/lgb/project/test.php/deployment-config.json'

### ISSUE THREAD

**Issue by benogle** [amoussard/sftp-deployment#41]
_From @pyhale on December 30, 2014 7:25_

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.13.0-43-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOTDIR, open '/home/lgb/project/test.php/deployment-config.json'

```
At fs.js:75

Error: ENOTDIR, open '/home/lgb/project/test.php/deployment-config.json'
  at Error (native)

```

### Commands

```
     -4:25.6 core:confirm (input.hidden-input)
  2x -2:04.8 remote-ftp:create-config (p.text.native-key-bindings)
     -1:26.3 remote-ftp:connect (atom-pane.pane.active)
     -1:21.5 remote-ftp:create-config (atom-pane.pane.active)
  2x -1:17.1 application:open-file (atom-pane.pane.active)
     -1:05.3 remote-ftp:create-config (input.hidden-input)
     -0:43.3 core:confirm (input.hidden-input)
     -0:00.0 sftp-deployment:mapToRemote (p.description.native-key-bindings)
```

### Config

```
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.3.0
SFTP-deployment, v0.5.0

# Dev
No dev packages
```

_Copied from original issue: atom/atom#4803_

**Comment by benogle** [comment]
This looks like a bug in the `sftp-deployment` package. Looks like it is trying to create a file (deployment-config.json) in a directory that is currently a file (/home/lgb/project/test.php).

**Comment by benogle** [comment]
_From @kevinsawicki on January 6, 2015 18:5_

Please report this against the https://atom.io/packages/sftp-deployment package.

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
