### ISSUE TITLE
Exposing coveralls secret token

### ISSUE THREAD

**Issue by kevinsimard** [amoussard/sftp-deployment#51]
Is there any reason why you are exposing your private token while it should be working out-of-the-box with Travis CI. Adding the script to 'after_script' in .travis.yml should do the job without having to expose the token.

> repo_token String

> The secret repo token for your repository, found at the bottom of your repository's page on Coveralls. This is useful if your job is running on a service we don't support out-of-the-box. If you choose to use the repo token, a new build will be created for every job.

**Comment by amoussard** [comment]
Hi @kevinsimard ,

Thank you for your remark, it's the first time I use Travis and Coveralls so... I will check that !
