### ISSUE TITLE
Configuration file not created

### ISSUE THREAD

**Issue by antidamage** [amoussard/sftp-deployment#54]
On Windows the configuration file is not being created by step 2 in the installation instructions. Simply nothing happens.

Additionally there's no indication in the documentation what the configuration file should be named.

**Comment by amoussard** [comment]
Hi @antidamage,

This problem is still there ?

Thank you.

**Comment by antidamage** [comment]
Sorry dude no idea. What is this in relation to?


Justin Cook
http://www.skull.co.nz
justin@skull.co.nz
021 2700 222
