### ISSUE TITLE
remotePath vs remote_path

### ISSUE THREAD

**Issue by qbolec** [amoussard/sftp-deployment#55]
The docs at https://github.com/amoussard/sftp-deployment names the key in the config using snake_case. The deployment-config.json file autogenerated by wizard uses camelCase.

Also, I get some strange "Cannot establish connection: path must be string" errors whenever I save something.

**Comment by marcoslhc** [comment]
It is `remote_path`.Is the only way I got it to work

**Comment by amoussard** [comment]
Hi guys,

I have fixed the documentation, you must use `removePath`.
