### ISSUE TITLE
Best way to use this package?

### ISSUE THREAD

**Issue by JonathanAaron** [amoussard/sftp-deployment#7]
I'm not sure how to get started using this package? I'm unable to log in with my credentials. What's the best way to get started with this app?

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This feature will be added at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
