### ISSUE TITLE
Cannot established connection: All configured authentication methods failed

### ISSUE THREAD

**Issue by C860** [amoussard/sftp-deployment#74]
Hi, I'm trying to use the config below:
```
{
    "type": "sftp",
    "host": "remoteIP",
    "username": "myusername",
    "password": "mypassword",
    "port": 32000,
    "remotePath": "/home",
    "uploadOnSave": false
}
```
but got an error:
> Cannot established connection: All configured authentication methods failed

But the same config on sublime sftp did well,is there something wrong with my config?

**Comment by dtsn** [comment]
I get the same error when connecting to one of my servers. It works fine on the other.

**Comment by C860** [comment]
@dtsn My server doesn't use the default port of 22, I guess this is one of the reason that cause the error.Does your server use the default port?

**Comment by WolfieZero** [comment]
I'm getting the same error (knowing it's all correct) and my port number is not the default either.

**Comment by C860** [comment]
OK, I found the problem: https://github.com/mscdex/ssh2/issues/238
> Our server does not use the "normal" password authentication mechanism, it uses the generic keyboard-interactive mechanism to display a password prompt instead.

`ssh2 module` support the 'keyboard-interactive' option which has not been used in `sftp-deployment`.

Now I use the https://github.com/mgrenier/remote-ftp instead because it support the 'keyboard-interactive' option.
