### ISSUE TITLE
Several simultaneous deploys

### ISSUE THREAD

**Issue by rafaelstz** [amoussard/sftp-deployment#75]
Feature to several simultaneous deploys. :smile:

**Comment by darol100** [comment]
This is duplicate issue from #12 .

There is a workaround but it require a little bit more work. 

https://github.com/amoussard/sftp-deployment/issues/12#issuecomment-140293991

**Comment by darol100** [comment]
I think we should close this issue since is a duplicate.

**Comment by rafaelstz** [comment]
Ok, thanks! :+1:
