### ISSUE TITLE
Path normalization

### ISSUE THREAD

**Issue by buschtoens** [amoussard/sftp-deployment#8]
Windows path notation style must be converted to Unix path notation style when uploading from Windows machines.

Example:

```json
{
  "type": "sftp",
  "host": "***",
  "user": "***",
  "password": "***",
  "port": "22",
  "remote_path": "~/test"
}
```

Uploading a test file then creates this directory structure.
```
~                     (home directory)
|
+-- ~test             (directory)
+-- ~\test\mytestfile (file)
```

The expected behaviour would be:
```
~                     (home directory)
|
+-- test              (directory)
    |
    +-- mytestfile    (file)
```

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
