### ISSUE TITLE
Readme.md out of date

### ISSUE THREAD

**Issue by sylistine** [amoussard/sftp-deployment#83]
The example deployment-config.json file in Readme.md says `"user":` but the default deployment-config.json file (created through Packages menu -> FTP/SFTP -> Map to Remote...) comes with `"username": `
Not sure which other settings are incorrect.

**Comment by amoussard** [comment]
Hi @sylistine,

It's an error in the documentation, I have merged a PR for this.

Thank you for your feedback.
