### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '~/.ssh/id_dsa'

### ISSUE THREAD

**Issue by Snake231088** [amoussard/sftp-deployment#9]
If i use short path in os x 10.9.1 instead the full path ( /Users/myuser/.ssh/id_dsa ) i got this error
![schermata 2014-06-08 alle 14 13 39](https://cloud.githubusercontent.com/assets/6999976/3211164/b790dfb6-ef06-11e3-9e24-9ae1268f12a0.png)
It's normal?

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
