### ISSUE TITLE
Anything on stderr throws RemoteDirectoryNotCreatedException

### ISSUE THREAD

**Issue by willotter** [amoussard/sftp-deployment#94]
https://github.com/amoussard/sftp-deployment/blob/master/lib/connections/SftpConnection.js#L70 this line of code catches anything on stderr and throws an exception. I experienced this because my server was incorrectly configured and was outputting `stdin: is not a tty` to stderr even though the command succeeded. I can't think of a elegant way to handle this. Maybe throw a more generic error as it may have been that mkdir hasn't failed. It was quite confusing because it says it can't create that directory when that isn't actually the error. I will submit a PR if I  get time.

**Comment by amoussard** [comment]
Hi @willotter,

I have merge your PR.
I will take a look to add this functionality where it's needed.

Thank your for your contribution :)
